services:
  - type: web
    name: mcp-supabase-bridge
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: NODE_ENV
        value: production
    autoDeploy: true